### ISSUE TITLE
Unable to add Athena Health source - Acess Control Allow Origin Header

### ISSUE THREAD

**Issue by starsoccer** [fastenhealth/fasten-sources#11]
When trying to setup athena health the following is logged in the console:

```Access to fetch at 'https://api.platform.athenahealth.com/oauth2/v1/token' from origin 'http://xxxxxxxxx:9090/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

**Comment by AnalogJ** [comment]
hey @starsoccer 
This should be fixed in the latest version of Fasten. Sorry about the delay!
