### ISSUE TITLE
Broken images in sources lookup page

### ISSUE THREAD

**Issue by joestump** [fastenhealth/fasten-sources#19]
<img width="1320" alt="image" src="https://github.com/fastenhealth/fasten-sources/assets/37667/7ca9b613-490e-4c52-987a-4e2536514d8e">

When I view source I noticed there's a missing `/` at the front. Not sure if it's meant to be a relative path or not:

<img width="484" alt="image" src="https://github.com/fastenhealth/fasten-sources/assets/37667/10cadfa2-b49a-4b6d-abc7-ff15bf8ebe62">

When I try to go to `/assets/sources/precision-healthcare-specialists.png` a white page loads and this shows up in the inspector: 

<img width="611" alt="image" src="https://github.com/fastenhealth/fasten-sources/assets/37667/34e63ac3-98de-48cb-b80d-a15fc2517458">

**Comment by AnalogJ** [comment]
yeah, theres ~27,000 supported healthcare institutions, but I've only found logos for ~19,000 of them. There's alot of blank boxes :( 

I need to figure out how to do imagesets and then find and add a fallback image

**Comment by AnalogJ** [comment]
this should now be fixed in `main`
