### ISSUE TITLE
[Source] Add Quest Diagnostics

### ISSUE THREAD

**Issue by samteezy** [fastenhealth/fasten-sources#35]
[According to Quest's website](https://newsroom.questdiagnostics.com/index.php?s=30664), they "touch" about 1/3 of Americans each year, so their reach is pretty large and would probably help be a draw for a number of users onto fasten.

**Comment by AnalogJ** [comment]
Update: Last communication was on April 2nd. Waiting on paperwork.

**Comment by AnalogJ** [comment]
Quest Developer env requirements:
- HTTP Proxy & IP Allowlisting.

**Comment by AnalogJ** [comment]
Update: using AWS Workspaces + NAT Gateway for whitelisting

**Comment by AnalogJ** [comment]
Update: Still waiting for Quest security team to finish their IP pen testing for Whitelisting

**Comment by AnalogJ** [comment]
IP Testing has been completed. Waiting final approvals to begin API integrations.

**Comment by AnalogJ** [comment]
```
time="2024-09-30T15:14:49Z" level=error msg="an error occurred while bulk importing resources from source: An error occurred during request https://api.questdiagnostics.com/resource-server/fhir/r4/Patient/xxxxxxxxxxx/$everything - 404 - 404 Not Found [{\"timestamp\":1727709289148,\"status\":404,\"error\":\"Not Found\",\"message\":\"No message available\",\"path\":\"/resource-server/fhir/r4/Patient/xxxxxxxxxx/$everything\"}]" type=ehi-export
```

use custom Patient everything path.
