### ISSUE TITLE
One Medical Support

### ISSUE THREAD

**Issue by verttex** [fastenhealth/fasten-sources#39]
Hey there,

I tried adding [One Medical](https://www.onemedical.com/) as a source and it tried to authenticate with a NextGen Healthcare portal that I've never seen before.

One is pretty popular where I am, especially with techy folk - definitely want to see if it would be possible to import my data!

Thanks!

**Comment by AnalogJ** [comment]
Sent another Email:

> Hi,
>
> I am writing on behalf of Fasten Health, Inc. to address a concern regarding selective API access provided by One Medical. We have noticed that while Apple Health and OneRecord have been granted access to your APIs, Fasten Health has not received similar permissions. This practice may constitute information blocking as defined under the 21st Century Cures Act and ONC’s Final Rule, which require equitable access to electronic health information (EHI).
>
> We are keen to resolve this matter promptly and ensure compliance with federal regulations, enhancing patient care through improved data interoperability. Could we discuss a pathway towards equitable API access for Fasten Health?
> 
> Thank you for your attention to this matter. We look forward to your response.

**Comment by AnalogJ** [comment]
If we don't hear back from them, I'll start filing information blocking tickets.

**Comment by noizwaves** [comment]
I've also sent a message requesting access 🤞

**Comment by AnalogJ** [comment]
OneMedical stated that they'll be sending me credentials soon.

**Comment by AnalogJ** [comment]
Received credentials. I'll do some development over the weekend to verify their integration.

**Comment by AnalogJ** [comment]
```
{
  "custom_definition": true,
  "platform_type": "onemedical",
  "should_override_redirect": false,
  "cors_relay_required": false,
  "override_redirect": "",
  "authorization_endpoint": "https://api.stage.1life.com/fhir-auth/authorize",
  "token_endpoint": "https://api.stage.1life.com/fhir-auth/oauth/token",
  "url": "https://api.stage.1life.com/fhir/4.0",
  "client_id": "xxxx",
  "redirect_uri": "https://lighthouse.fastenhealth.com/sandbox/callback/onemedical",
  "grant_types_supported": [
    "authorization_code"
  ],
  "response_types_supported": [
    "code"
  ],
  "response_modes_supported": [
    "fragment"
  ],
  "aud": "https://api.stage.1life.com/fhir/4.0",
  "scopes_supported": [
    "fhirUser",
    "openid",
    "profile",
    "patient/*.read"
  ],
  "confidential": false,
  "confidential_endpoint": "",
  "pkce": true,
  "code_challenge_methods_supported": [
    "S256"
  ],
  "issuer": "https://api.stage.1life.com/fhir/4.0"
}
```

# Status

- Waiting for response containing Sandbox credentials

**Comment by AnalogJ** [comment]
Hey @noizwaves @ignacio82 @verttex @sjafferali @zacharyneveu 
Can you all pull the latest docker image (once it finishes building) and try connecting One Medical?

I've confirmed its working using my own account, but I'd like a second confirmation as well :)

**Comment by ignacio82** [comment]
Do we need to message them to get credentials? When I asked a while ago
they just sent me a PDF and told me what I wanted was not possible. Would
you mind sharing the message you sent to get your credentials?

**Comment by AnalogJ** [comment]
no additional credentials required, I just logged in with my standard One Medical account email address and password.

**Comment by ignacio82** [comment]
confirming that it works

**Comment by AnalogJ** [comment]
fantastic, thanks @ignacio82 !

**Comment by sjafferali** [comment]
Thanks for getting this implemented!
