### ISSUE TITLE
One Medical With Providence

### ISSUE THREAD

**Issue by Nisan-Stiennon** [fastenhealth/fasten-sources#43]
There's a portal with id `dd04fec0-2dd4-4018-8e45-e6da6589c3f1` and name `One Medical Group`. Based on the logo, I assume it's for One Medical With Providence, a DBA of Providence Health & Services Oregon. The name should probably be changed to "One Medical With Providence", so as not to confuse users looking for One Medical's main patient portal.

(Separately, #39 is about adding One Medical.)

**Comment by AnalogJ** [comment]
This is fixed (and One Medical should be added soon!)
Thanks!
