### ISSUE TITLE
Ascension Seton source notes

### ISSUE THREAD

**Issue by ideamatrix** [fastenhealth/fasten-sources#8]
In the source list, Ascension Seton is identified as a user of Cerner. That only applies to hospital records, Records from visits to Ascension clinics and doctors' offices are in Athena. Additional notes below:

Ascension Seton - Hospital records are in Oracle/Cerner and records from doctor visits are in Athena (Note that some hospital records are also in Athena, especially if patient's provider has seen them both in the hospital and as an outpatient). Cannot segment mental/behavioral health from other records. Records downloaded via patient portal are only available in a zip file containing PDF and CDA XSL StyleSheet. No instructions are provided to patient to explain why the XSL stylesheet is provided or can be used. Patient can also send records via Direct Exchange email (which potentially provides structured data).

Ascension adds information from data brokers and other sources to patient records for Social Determinants of Health initiatives. The socioeconomic data collected is not available to patients, though they're the subject of the income and other PII data collected. Patients are also prevented from accessing their medical data that is added to their medical records by Google Health AI and Project Nightingale.

Ascension notes that full medical records are only available via Swellbox (Ciox/Datavant).

Hospital visit records: https://seton.consumeridp.us-1.healtheintent.com/saml2/sso/login?authenticationRequestId=84f65123-d979-404e-829f-3726371a33b0
Doctor visit records: https://8363-1.portal.athenahealth.com/
Full medical records: https://www.swellbox.com/ascension-texas-seton-wizard.html

**Comment by AnalogJ** [comment]
Hey @ideamatrix 
Thanks for all the information about Ascension. Athena will be supported as well, I'm in the process of testing out our integration at the moment - https://github.com/fastenhealth/fasten-sources/blob/main/PLATFORM_LIST.md

**Comment by AnalogJ** [comment]
Hey @ideamatrix 
I just added support for Athena providers in the main branch. Would you be willing to help me test it out?

Just pull down the `ghcr.io/fastenhealth/fasten-onprem:main` docker image and test it with your AthenaHealth provider(s):

```bash
docker pull ghcr.io/fastenhealth/fasten-onprem:main 
docker run --rm -p 9090:8080 ghcr.io/fastenhealth/fasten-onprem:main 
```

If you run into any issues, please respond below, or message me in the Fasten Discord

**Comment by ideamatrix** [comment]
Everything was looking good until I was redirected back to Fasten.

Steps:

1. I found Ascension Medical Group Seton in the list and clicked it, then clicked "Connect".
2. I was directed to the sign-in page for Ascension Medical Group on Athena and signed in.
3. I selected my patient record from the list (there was only one record available)
4. The sign-in went fine, and all selections in the list of permissions were pre-selected.
5. I received the confirmation page: "Your ATHENA account has been securely connected to FASTEN."
6. I was redirected back to Fasten and Ascension Medical Group Seton was listed in my Connected Sources, with the progress bar about 2/3 complete as soon as the page loaded.
7. The progress bar did not move, and after approx. 10 seconds, I received this error:
_An error occurred while accessing ascension-medica-group-seton: '{}'_

![image](https://github.com/fastenhealth/fasten-sources/assets/49213109/830e03d9-79b0-45e1-802b-8d38eaad366e)

**Comment by AnalogJ** [comment]
Apologies, I've been working on a Desktop version of Fasten, and I made a breaking change. A new docker image is building which should fix this issue.

**Comment by ideamatrix** [comment]
I tried a few times, pulling a new image each time. Same error message.

**Comment by AnalogJ** [comment]
Hey @ideamatrix are you on Discord by chance? And/Or would you be willing to do a screen sharing session with me? I'd like to figure out if this is still an issue, and what's causing it.

https://calendly.com/jason-kulatunga/

**Comment by AnalogJ** [comment]
hey @ideamatrix 
This should be fixed in the latest version of Fasten. Can you try it out?

**Comment by ideamatrix** [comment]
Apologies I missed your earlier comment. It's working, and data imported without errors. It was difficult to find the right provider in the list - Ascension uses a huge number of separate EHR's (easily 80+ if logins need to use the correct hostnames for Athena, Epic, and Cerner). I'll start making some updates in Toolbox.

A few notes after testing for a couple hours:
- Not importing medications or clinical notes
- Care Team is empty in the interface, but shows in JSON.
- Care Team JSON is incomplete, full team only shows in Practitioners (and shows correctly in the interface)
- Organization names are incorrect - Seton populates "name" with a code, such as `SFC_PEDI GASTRO_STRCT 401`. The full name is `patientFacingName` as in the JSON snippet below:
```
"extension": [
	{
		"extension": [
			{
				"url": "patientFacingName",
				"valueString": "Dell Children's Medical Group Gastroenterology Department"
			}
		],
		"url": "https://fhir.athena.io/StructureDefinition/ah-location-department-details"
	}
]
```

Some of those may be specific to either Fasten or Athena. Let me know if you'd like me to create issues for any of the items above.
